version: '3.4'
services:
  webdatabasemanagement:
    image: webdatabasemanagement
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"