# Generated by Django 2.0.6 on 2018-06-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='num_ID',
        ),
    ]
